In [1]:
import pandas as pd

In [3]:
# BOY MAP Data 
boy = pd.read_csv("Data/MAP_BOY_2020-21.csv") 

# MOY MAP Data 
moy = pd.read_csv("Data/MAP_MOY_2020-21.csv") 

# student demographic data
demographics = pd.read_csv("Data/Student_Demographics_2020-21.csv")

# EDA

## BOY MAP DATA

In [4]:
boy.head()

,Fake_Student_ID,TermName,DistrictName,SchoolName,StudentDateOfBirth,Grade,Subject,Course,TestType,TestName,TestStartDate,TestStartTime,TestDurationMinutes,TestRITScore,TestStandardError,TestPercentile,AchievementQuintile,PercentCorrect
0,2115893,Fall 2020-2021,Dallas Independent School District (DISD),Harry C Withers Elementary School,9/12/2012,2,Mathematics,Math K-12,Survey With Goals,Growth: Math 2-5 TX 2012,9/29/2020,9:04:36,38,187,3.0,82,High,50
1,2115893,Fall 2020-2021,Dallas Independent School District (DISD),Harry C Withers Elementary School,9/12/2012,2,Language Arts,Reading,Survey With Goals,Growth: Reading 2-5 TX 2017,9/22/2020,8:45:17,94,197,3.5,95,High,60
2,5090051,Fall 2020-2021,Dallas Independent School District (DISD),Louise Wolff Kahn Elementary School,5/14/2014,1,Mathematics,Math K-12,Survey With Goals,Growth: Math K-2 TX 2012,9/21/2020,9:19:13,37,153,3.2,29,LoAvg,49
3,5090051,Fall 2020-2021,Dallas Independent School District (DISD),Louise Wolff Kahn Elementary School,5/14/2014,1,Language Arts,Reading (Spanish),Survey With Goals,Growth: Spanish Reading K-2 TX 2017,9/21/2020,10:57:10,18,132,3.5,9,Low,37
4,8221829,Fall 2020-2021,Dallas Independent School District (DISD),Stephen C Foster Elementary School,10/5/2012,2,Mathematics,Math K-12,Survey With Goals,Growth: Math 2-5 TX 2012,9/21/2020,9:07:44,41,142,3.3,1,Low,30

In [5]:
#columns in dataframe
boy.columns

Index(['Fake_Student_ID', 'TermName', 'DistrictName', 'SchoolName',
       'StudentDateOfBirth', 'Grade', 'Subject', 'Course', 'TestType',
       'TestName', 'TestStartDate', 'TestStartTime', 'TestDurationMinutes',
       'TestRITScore', 'TestStandardError', 'TestPercentile',
       'AchievementQuintile', 'PercentCorrect'],
      dtype='object')

In [6]:
#total number of grades represented 
boy['Grade'].unique()

array([2, 1])

Data is from students in 1st & 2nd grade.

In [7]:
#Districts 
boy['DistrictName'].unique()

array(['Dallas Independent School District (DISD)'], dtype=object)

In [12]:
#schools represented  
print(f"Number of Schools {len(boy['SchoolName'].unique())}")
print(boy['SchoolName'].unique())

Number of Schools 149
['Harry C Withers Elementary School' 'Louise Wolff Kahn Elementary School'
 'Stephen C Foster Elementary School' 'Ida B. Wells Academy'
 'KB Polk Center for Academically Talented & Gifted'
 'William Lipscomb Elementary School' 'Chapel Hill Preparatory'
 'Mockingbird Elementary School' 'Obadiah Knight Elementary School'
 'Maple Lawn Elementary School'
 'Celestino Mauricio Soto Jr Elementary School'
 'S S Conner Elementary School' 'L L Hotchkiss Elementary School'
 'Edna Rowe Elementary School' 'Central Elementary School'
 'Charles Rice Learning Center' 'Anson Jones Elementary School'
 'James Bowie Elementary School' 'Arturo Salazar Elementary School'
 'Casa View Elementary School' 'Winnetka Elementary School'
 'Arthur Kramer Elementary School'
 'Thomas L Marsalis Elementary STEAM Academy'
 'Lee A McShan Jr Elementary School' 'Edwin J Kiest Elementary School'
 'Larry G Smith Elementary School' 'George Peabody Elementary School'
 'W W Bushman Elementary School' 'Daniel Webster Elementary School'
 'Solar Prep for Boys at John F. Kennedy'
 'John F Peeler Elementary School'
 'Henry B Gonzalez Personalized Learning Academy'
 'John Neely Bryan Elementary School' 'Charles A Gill Elementary School'
 'Frank Guzick Elementary School' 'J N Ervin Elementary School'
 'Jose Joe May Elementary School' 'Martin Weiss Elementary School'
 'Lakewood Elementary School' 'Nancy Moseley Elementary School'
 'Seagoville Elementary School' 'John W Runyon Elementary School'
 'Dan D Rogers Elementary School' 'Mount Auburn STEAM Academy'
 'F P Caillet Elementary School' 'Seagoville North Elementary School'
 'Herbert Marcus Elementary School' 'Elisha M Pease Elementary School'
 'Mark Twain Leadership Vanguard'
 'Hall Personalized Learning Academy at Oak Cliff'
 'Thomas Tolbert Elementary School' 'Leslie A Stemmons Elementary School'
 'Clara Oliver Elementary School' 'William M Anderson Elementary School'
 'Richard Lagow Elementary School' 'Ronald E McNair Elementary School'
 'Highland Meadows Elementary School' 'Wilmer-Hutchins Elementary School'
 'George W Truett Elementary School' 'Geneva Heights Elementary School'
 'C A Tatum Jr Elementary School' 'John Ireland Elementary School'
 'Martha Turner Reilly Elementary School'
 'Rosemont Lower - Chris V Semos Building'
 'Adelfa Botello Callejo Elementary School'
 'Cedar Crest Elementary School'
 'H.I. Holland Elementary School at Lisbon'
 'George Herbert Walker Bush Elementary School' 'Bayles Elementary School'
 'Urban Park Elementary School' 'Mary McLeod Bethune Elementary School'
 'Frederick Douglass Elementary School'
 'Everette Lee Degolyer Elementary School' 'Walnut Hill Elementary School'
 'Gabe P Allen Charter School' 'Harry Stone Montessori Academy'
 'Eduardo Mata Montessori School' 'Joseph J Rhoads Elementary School'
 'Solar Prep School for Girls at James B Bonham'
 'Cesar Chavez Learning Center' 'L O Donald Elementary School'
 'Trinity Heights Gifted and Talented School'
 'Ben Milam Elementary School' 'W A Blair Elementary School'
 'San Jacinto Elementary School'
 'Thelma Elizabeth Page Richardson Elementary School'
 'John J Pershing Elementary School' 'N W Harllee Early Childhood Center'
 'B H Macon Elementary School'
 'Leonides Gonzalez Cigarroa MD Elementary School'
 'Barbara Jordan Elementary School' 'Leila P Cowart Elementary School'
 'Eladio R Martinez Learning Center' 'Rufus C Burleson Elementary School'
 'Esperanza Hope Medrano Elementary School' 'Anne Frank Elementary School'
 'Tom C Gooch Elementary School' 'George B. Dealey Montessori Academy'
 'Gilbert Cuellar Sr Elementary School' 'John Q Adams Elementary School'
 'Nathan Adams Elementary School' 'Ebby Halliday Elementary School'
 'Clinton P Russell Elementary School'
 'Margaret B Henderson Elementary School'
 'Julian T Saldivar Elementary School' 'Kleberg Elementary School'
 'Arcadia Park Elementary School'
 'Montessori Academy at Onesimo Hernandez'
 'Ignacio Zaragoza Elementary School'
 'Felix G Botello Personalized Learning Elementary'
 'Ascher Silberstein Elementary School' 'Julius Dorsey Elementary School'
 'Jimmie Tyler Brashear Elementary School' 'T G Terry Elementary School'
 'Lida Hooe Elementary School' 'Nancy J Cochran Elementary School'
 'Annie Webb Blanton Elementary School'
 'Jerry R Junkins Elementary School' 'Reinhardt Elementary School'
 'Victor H Hexter Elementary School'
 'Martin Luther King Jr Learning Center'
 'Lorenzo De Zavala Elementary School' 'Oran M Roberts Elementary School'
 'David G Burnet Elementary School' 'Edward Titche Elementary School'
 'Sidney Lanier Expressive Arts Vanguard' 'Stevens Park Elementary School'
 'Hogg New Tech Center' 'John H Reagan Elementary School'
 'Pleasant Grove Elementary School'
 'Nathaniel Hawthorne Elementary School'
 'Birdie Alexander Elementary School' 'Preston Hollow Elementary School'
 'Maria Moreno STEAM Academy' 'Umphrey Lee Elementary School'
 'J P Starks Elementary School' 'Jack Lowe Sr Elementary School'
 'Whitney M Young Jr Elementary School'
 'Eddie Bernice Johnson Elementary School'
 'Alex Sanger Preparatory School' 'Paul L Dunbar Learning Center'
 'C F Carr Elementary School' 'R L Thornton Elementary School'
 'Houston Personalized Learning' 'Harrell Budd Elementary School'
 'Adelle Turner Elementary School' 'John W Carpenter Elementary School'
 'William B Miller Elementary School'
 'Jill Stone Elementary School at Vickery Meadow']

All data is from DISD School, there are 149 schools represented in this data set.

In [16]:
#descriptive statistics for quantitative columns
boy[['TestDurationMinutes', 'TestRITScore', 'TestStandardError', 'TestPercentile','PercentCorrect']].describe()

,TestDurationMinutes,TestRITScore,TestStandardError,TestPercentile,PercentCorrect
count,38648.000000,38648.000000,38648.000000,38648.000000,38648.000000
mean,41.486416,162.801671,3.281049,45.061374,47.387032
std,27.827051,18.215424,0.289124,31.295397,8.821543
min,6.000000,102.000000,2.900000,1.000000,8.000000
25%,23.000000,150.000000,3.100000,17.000000,44.000000
50%,34.000000,162.000000,3.200000,41.000000,49.000000
75%,51.000000,174.000000,3.400000,72.000000,53.000000
max,339.000000,259.000000,13.400000,99.000000,100.000000